#.replace()
sample4 = "This is our samplessssss fourth sample string for the day."
print(sample4.replace(" sample ","REPLACED"))

#slicing --> allows us to extract (parse) snippets of the text out.
sample5 = "This is our fifth sample string for the day."
print(sample5[0]) #prints letter at index 0
print(sample5[:5]) #prints everything up till 5
print(sample5[0:]) #prints whole string
print(sample5[0:10:2]) #gives first 10 characters, every other

#instructor demo
#understand
'''is pangram
 - all letters present at least one time
 - input: string, any case
 - return: boolean T/F
'''

#plan - hint: python has a built in function, isalpha() that might help
'''
1. working with unknown size string - clean up the string to know the expected format
2. wanna check for all 26 letters using a dictionary
2.5 we need to use a for loop to iterate thru each char
    - key -> letter, value -> true/false
3. count # keys in dictionary, if == 26, (return value)
'''
def is_pangram(sentence):
    lowercase_sentence = sentence.lower()
    letter_appearances = {} #key letter, value T/F

    for char in lowercase_sentence:
        if char.isalpha() == False:
            pass #pass == ignore, continue == jump to next iteration
        if char not in letter_appearances: #first time seeing it
            letter_appearances[char] = True
    
    if(len(letter_appearances) == 26):
        return True
    else:
        return False

inputSample = "The quick brown fox jumps over the lazy dog."


########################## BREAKOUT ROOM PRACTICE -- UNIT 3 ##########################

'''
1. Call the function so that it prints out the following to the console:
Pikachu I choose you!
Charizard I choose you!
Eevee I choose you!
'''
def choose_pokemon(my_pokemon):
	for pokemon in my_pokemon:
		print(f"{pokemon} I choose you!")

choose_pokemon(["Pikachu", "Charizard", "Eevee"])

'''
2. Write a function rotate_left() that takes in a string s and an integer n 
as parameters. The function returns a new string with the first n 
characters moved to the end of the string where 1 <= n <= len(str).
'''
def rotate_left(s, n):
    rotated = s[n:]+s[:n]
    return rotated

s = "rotation"
print(rotate_left(s, 2))


# 3
# Write a function first_repeated_char() that takes in a string s as a parameter and returns the
# index of the first repeated character in the string. Uppercase and lowercase letters are 
# considered different characters, and the function returns None if there are no repeated characters.

'''
def first_repeated_char(s):
    seen = set()
    for i, char in enumerate(s):
        if char in seen:
            reuturn i
        seen.add(char)

    return none

   # first_repeated_char() 
'''

'''
4. Write a function find_difference() that takes two strings as parameters. 
The second string is generated by shuffling the first string and adding 
one more letter at a random position. Search for and return the added letter.
'''
def find_difference(s1, s2):
    letter = ""
    for char in s2:
        if char not in s1:
            letter = char
    
    return letter

s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))

def roman_to_int(s):
    pass

'''
5. Write a function that takes in a string s and returns the length of 
the longest substring without repeating characters.
'''
def length_of_longest_substring(s):
    prev_char = ""
    count = 0
    for curr_char in s:
        if curr_char != prev_char:
            count+=1
            prev_char = curr_char
        else:
            return count

s = "abcdeefghhhhh"
count = length_of_longest_substring(s)
print(count)

s2 = "aaaaaaaaaaaaaaa"
count = length_of_longest_substring(s2)
print(count)


'''
6. Roman Numerals are represented by seven different symbols (I, V, X, L, C, D, and M) and have these corresponding values:

I = 1 V = 5
X = 10 L = 50
C = 100 D = 500
M = 1000

For example, 2 is written as II, which is just two ones added together.
12 is written as XII, which is simply X + II.
The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for 4 is not IIII. Instead, the number 4 is written as IV.

Because the I is before the V, we subtract it to equal 4. The same principle applies to the number 9, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9
X can be placed before L (50) and C (100) to make 40 and 90
C can be placed before D (500) and M (1000) to make 400 and 900
Write a function roman_to_int() that takes in a string s that makes up a roman numeral. The function should return the integer value of s.

Example Usage:

s = "XL"
print(roman_to_int(s))

s2 = "LVIII"
print(roman_to_int(s2))

s3 = "MCMXCIV"
print(roman_to_int(s3))
Example Output:

40
58
1994
'''

def roman_to_int(s):
    meanings = {"I":1, "V":5, "X":10, "L":50, "C":100, "D":500, "M":1000}